version: '2.3'

services:
  proxy:
    build: ./services/frontend
    restart: unless-stopped
    ports:
      - 4000:80
    environment:
      - BACKEND_HOST=backend
    volumes:
      - ./services/frontend/nginx.tmpl:/etc/nginx/nginx.tmpl
    depends_on:
      - backend

  backend:
    build: ./services/backend
    restart: unless-stopped
    environment:
      # - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db/data
    volumes:
      - ./services/backend:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mdillon/postgis:9.6-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    command: ["-c", "max_connections=200"]